# Generated by Django 5.2.6 on 2025-09-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=2, max_length=11),
            preserve_default=False,
        ),
    ]
